In [1]:
import numpy as np
import pandas as pd

In [2]:
datawith = pd.read_csv('with.csv')
datawith.loc[datawith['Married']=="Yes",'Married']=1
datawith.loc[datawith['Married']=='No','Married']=0
datawith.loc[datawith['Education']=="Graduate",'Education']=1
datawith.loc[datawith['Education']=='Not Graduate','Education']=0
datawith.loc[datawith['Self_Employed']=="Yes",'Self_Employed']=1
datawith.loc[datawith['Self_Employed']=='No','Self_Employed']=0
datawith.loc[datawith['Property_Area']=="Urban",'Property_Area']=0
datawith.loc[datawith['Property_Area']=='Semiurban','Property_Area']=1
datawith.loc[datawith['Property_Area']=='Rural', 'Property_Area']=2
datawith.head()

,Unnamed: 0,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,0,0,1,0,5849,0.0,146.412162,360.0,1.0,0,1
1,1,1,1,1,0,4583,1508.0,128.000000,360.0,1.0,2,0
2,2,1,0,1,1,3000,0.0,66.000000,360.0,1.0,0,1
3,3,1,0,0,0,2583,2358.0,120.000000,360.0,1.0,0,1
4,4,0,0,1,0,6000,0.0,141.000000,360.0,1.0,0,1

In [3]:
datawo = pd.read_csv('without.csv')
datawo.loc[datawo['Married']=="Yes",'Married']=1
datawo.loc[datawo['Married']=='No','Married']=0
datawo.loc[datawo['Education']=="Graduate",'Education']=1
datawo.loc[datawo['Education']=='Not Graduate','Education']=0
datawo.loc[datawo['Self_Employed']=="Yes",'Self_Employed']=1
datawo.loc[datawo['Self_Employed']=='No','Self_Employed']=0
datawo.loc[datawo['Property_Area']=="Urban",'Property_Area']=0
datawo.loc[datawo['Property_Area']=='Semiurban','Property_Area']=1
datawo.loc[datawo['Property_Area']=='Rural', 'Property_Area']=2
datawo.head()

,Unnamed: 0,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,333,1,0,1,0,63337,0.0,490.0,180,1,0,1
1,171,1,3,1,0,51763,0.0,700.0,300,1,0,1
2,155,1,3,1,0,39999,0.0,600.0,180,0,1,1
3,185,1,0,1,1,39147,4750.0,120.0,360,1,1,1
4,443,0,1,1,0,37719,0.0,152.0,360,1,1,1

In [4]:
X1 = datawith.drop("Loan_Status", axis=1)
y1 = datawith["Loan_Status"]
print(X1.shape, y1.shape)

(614, 11) (614,)

In [5]:
X2 = datawo.drop("Loan_Status", axis=1)
y2 = datawo["Loan_Status"]
print(X2.shape, y2.shape)

(599, 11) (599,)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical

X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, random_state=1, stratify=y1)
X1_scaler = StandardScaler().fit(X1_train)
X1_train_scaled = X1_scaler.transform(X1_train)
X1_test_scaled = X1_scaler.transform(X1_test)


# Step 1: Label-encode data set
label1_encoder = LabelEncoder()
label1_encoder.fit(y1_train)
encoded_y1_train = label1_encoder.transform(y1_train)
encoded_y1_test = label1_encoder.transform(y1_test)

# Step 2: Convert encoded labels to one-hot-encoding
y1_train_categorical = to_categorical(encoded_y1_train)
y1_test_categorical = to_categorical(encoded_y1_test)

Using TensorFlow backend.

In [7]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, random_state=1, stratify=y2)
X2_scaler = StandardScaler().fit(X2_train)
X2_train_scaled = X2_scaler.transform(X2_train)
X2_test_scaled = X2_scaler.transform(X2_test)


# Step 1: Label-encode data set
label2_encoder = LabelEncoder()
label2_encoder.fit(y2_train)
encoded_y2_train = label2_encoder.transform(y2_train)
encoded_y2_test = label2_encoder.transform(y2_test)

# Step 2: Convert encoded labels to one-hot-encoding
y2_train_categorical = to_categorical(encoded_y2_train)
y2_test_categorical = to_categorical(encoded_y2_test)

In [8]:
from keras.models import Sequential
from keras.layers import Dense

model1 = Sequential()
model1.add(Dense(units=100, activation='relu', input_dim=11))
model1.add(Dense(units=100, activation='relu'))
model1.add(Dense(units=2, activation='softmax'))

model2 = Sequential()
model2.add(Dense(units=100, activation='relu', input_dim=11))
model2.add(Dense(units=100, activation='relu'))
model2.add(Dense(units=2, activation='softmax'))

In [9]:
model1.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
model1.fit(
    X1_train_scaled,
    y1_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 0s - loss: 0.6311 - acc: 0.6935
Epoch 2/100
 - 0s - loss: 0.5191 - acc: 0.8109
Epoch 3/100
 - 0s - loss: 0.4631 - acc: 0.8261
Epoch 4/100
 - 0s - loss: 0.4339 - acc: 0.8261
Epoch 5/100
 - 0s - loss: 0.4202 - acc: 0.8261
Epoch 6/100
 - 0s - loss: 0.4067 - acc: 0.8326
Epoch 7/100
 - 0s - loss: 0.3989 - acc: 0.8326
Epoch 8/100
 - 0s - loss: 0.3891 - acc: 0.8391
Epoch 9/100
 - 0s - loss: 0.3797 - acc: 0.8391
Epoch 10/100
 - 0s - loss: 0.3711 - acc: 0.8435
Epoch 11/100
 - 0s - loss: 0.3659 - acc: 0.8457
Epoch 12/100
 - 0s - loss: 0.3532 - acc: 0.8609
Epoch 13/100
 - 0s - loss: 0.3453 - acc: 0.8587
Epoch 14/100
 - 0s - loss: 0.3401 - acc: 0.8543
Epoch 15/100
 - 0s - loss: 0.3340 - acc: 0.8587
Epoch 16/100
 - 0s - loss: 0.3242 - acc: 0.8630
Epoch 17/100
 - 0s - loss: 0.3146 - acc: 0.8652
Epoch 18/100
 - 0s - loss: 0.3096 - acc: 0.8696
Epoch 19/100
 - 0s - loss: 0.3038 - acc: 0.8674
Epoch 20/100
 - 0s - loss: 0.2981 - acc: 0.8739
Epoch 21/100
 - 0s - loss: 0.2920 - acc: 0.8783
Epoch 22/100
 - 0s - loss: 0.2844 - acc: 0.8783
Epoch 23/100
 - 0s - loss: 0.2791 - acc: 0.8913
Epoch 24/100
 - 0s - loss: 0.2765 - acc: 0.8848
Epoch 25/100
 - 0s - loss: 0.2670 - acc: 0.8978
Epoch 26/100
 - 0s - loss: 0.2632 - acc: 0.8935
Epoch 27/100
 - 0s - loss: 0.2527 - acc: 0.8891
Epoch 28/100
 - 0s - loss: 0.2494 - acc: 0.9065
Epoch 29/100
 - 0s - loss: 0.2461 - acc: 0.8957
Epoch 30/100
 - 0s - loss: 0.2391 - acc: 0.9022
Epoch 31/100
 - 0s - loss: 0.2446 - acc: 0.8978
Epoch 32/100
 - 0s - loss: 0.2336 - acc: 0.9043
Epoch 33/100
 - 0s - loss: 0.2300 - acc: 0.9065
Epoch 34/100
 - 0s - loss: 0.2305 - acc: 0.9022
Epoch 35/100
 - 0s - loss: 0.2223 - acc: 0.9152
Epoch 36/100
 - 0s - loss: 0.2139 - acc: 0.9217
Epoch 37/100
 - 0s - loss: 0.2118 - acc: 0.9130
Epoch 38/100
 - 0s - loss: 0.2021 - acc: 0.9152
Epoch 39/100
 - 0s - loss: 0.1985 - acc: 0.9239
Epoch 40/100
 - 0s - loss: 0.1927 - acc: 0.9304
Epoch 41/100
 - 0s - loss: 0.1916 - acc: 0.9348
Epoch 42/100
 - 0s - loss: 0.1855 - acc: 0.9239
Epoch 43/100
 - 0s - loss: 0.1855 - acc: 0.9391
Epoch 44/100
 - 0s - loss: 0.1778 - acc: 0.9326
Epoch 45/100
 - 0s - loss: 0.1760 - acc: 0.9522
Epoch 46/100
 - 0s - loss: 0.1776 - acc: 0.9370
Epoch 47/100
 - 0s - loss: 0.1721 - acc: 0.9435
Epoch 48/100
 - 0s - loss: 0.1625 - acc: 0.9391
Epoch 49/100
 - 0s - loss: 0.1614 - acc: 0.9457
Epoch 50/100
 - 0s - loss: 0.1664 - acc: 0.9348
Epoch 51/100
 - 0s - loss: 0.1587 - acc: 0.9413
Epoch 52/100
 - 0s - loss: 0.1615 - acc: 0.9457
Epoch 53/100
 - 0s - loss: 0.1507 - acc: 0.9478
Epoch 54/100
 - 0s - loss: 0.1430 - acc: 0.9500
Epoch 55/100
 - 0s - loss: 0.1385 - acc: 0.9587
Epoch 56/100
 - 0s - loss: 0.1352 - acc: 0.9630
Epoch 57/100
 - 0s - loss: 0.1353 - acc: 0.9522
Epoch 58/100
 - 0s - loss: 0.1361 - acc: 0.9522
Epoch 59/100
 - 0s - loss: 0.1313 - acc: 0.9630
Epoch 60/100
 - 0s - loss: 0.1267 - acc: 0.9522
Epoch 61/100
 - 0s - loss: 0.1268 - acc: 0.9674
Epoch 62/100
 - 0s - loss: 0.1199 - acc: 0.9609
Epoch 63/100
 - 0s - loss: 0.1167 - acc: 0.9652
Epoch 64/100
 - 0s - loss: 0.1152 - acc: 0.9609
Epoch 65/100
 - 0s - loss: 0.1175 - acc: 0.9565
Epoch 66/100
 - 0s - loss: 0.1133 - acc: 0.9630
Epoch 67/100
 - 0s - loss: 0.1085 - acc: 0.9696
Epoch 68/100
 - 0s - loss: 0.1120 - acc: 0.9587
Epoch 69/100
 - 0s - loss: 0.1057 - acc: 0.9609
Epoch 70/100
 - 0s - loss: 0.1077 - acc: 0.9696
Epoch 71/100
 - 0s - loss: 0.1010 - acc: 0.9717
Epoch 72/100
 - 0s - loss: 0.0970 - acc: 0.9717
Epoch 73/100
 - 0s - loss: 0.0917 - acc: 0.9739
Epoch 74/100
 - 0s - loss: 0.0922 - acc: 0.9739
Epoch 75/100
 - 0s - loss: 0.0975 - acc: 0.9652
Epoch 76/100
 - 0s - loss: 0.1054 - acc: 0.9630
Epoch 77/100
 - 0s - loss: 0.0938 - acc: 0.9717
Epoch 78/100
 - 0s - loss: 0.0945 - acc: 0.9652
Epoch 79/100
 - 0s - loss: 0.0874 - acc: 0.9652
Epoch 80/100
 - 0s - loss: 0.0825 - acc: 0.9848
Epoch 81/100
 - 0s - loss: 0.0834 - acc: 0.9739
Epoch 82/100
 - 0s - loss: 0.0816 - acc: 0.9783
Epoch 83/100
 - 0s - loss: 0.0784 - acc: 0.9717
Epoch 84/100
 - 0s - loss: 0.0739 - acc: 0.9848
Epoch 85/100
 - 0s - loss: 0.0750 - acc: 0.9717
Epoch 86/100
 - 0s - loss: 0.0770 - acc: 0.9804
Epoch 87/100
 - 0s - loss: 0.0734 - acc: 0.9739
Epoch 88/100
 - 0s - loss: 0.0698 - acc: 0.9891
Epoch 89/100
 - 0s - loss: 0.0697 - acc: 0.9804
Epoch 90/100
 - 0s - loss: 0.0727 - acc: 0.9804
Epoch 91/100
 - 0s - loss: 0.0660 - acc: 0.9826
Epoch 92/100
 - 0s - loss: 0.0679 - acc: 0.9826
Epoch 93/100
 - 0s - loss: 0.0617 - acc: 0.9913
Epoch 94/100
 - 0s - loss: 0.0618 - acc: 0.9783
Epoch 95/100
 - 0s - loss: 0.0666 - acc: 0.9848
Epoch 96/100
 - 0s - loss: 0.0602 - acc: 0.9848
Epoch 97/100
 - 0s - loss: 0.0578 - acc: 0.9870
Epoch 98/100
 - 0s - loss: 0.0547 - acc: 0.9891
Epoch 99/100
 - 0s - loss: 0.0538 - acc: 0.9870
Epoch 100/100
 - 0s - loss: 0.0569 - acc: 0.9848

In [10]:
model2.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])
model2.fit(
    X2_train_scaled,
    y2_train_categorical,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
 - 0s - loss: 0.5888 - acc: 0.7617
Epoch 2/100
 - 0s - loss: 0.4808 - acc: 0.8285
Epoch 3/100
 - 0s - loss: 0.4200 - acc: 0.8486
Epoch 4/100
 - 0s - loss: 0.4059 - acc: 0.8508
Epoch 5/100
 - 0s - loss: 0.3974 - acc: 0.8508
Epoch 6/100
 - 0s - loss: 0.3863 - acc: 0.8508
Epoch 7/100
 - 0s - loss: 0.3761 - acc: 0.8508
Epoch 8/100
 - 0s - loss: 0.3699 - acc: 0.8508
Epoch 9/100
 - 0s - loss: 0.3668 - acc: 0.8508
Epoch 10/100
 - 0s - loss: 0.3574 - acc: 0.8508
Epoch 11/100
 - 0s - loss: 0.3523 - acc: 0.8508
Epoch 12/100
 - 0s - loss: 0.3534 - acc: 0.8597
Epoch 13/100
 - 0s - loss: 0.3456 - acc: 0.8597
Epoch 14/100
 - 0s - loss: 0.3360 - acc: 0.8552
Epoch 15/100
 - 0s - loss: 0.3389 - acc: 0.8664
Epoch 16/100
 - 0s - loss: 0.3353 - acc: 0.8619
Epoch 17/100
 - 0s - loss: 0.3179 - acc: 0.8664
Epoch 18/100
 - 0s - loss: 0.3171 - acc: 0.8552
Epoch 19/100
 - 0s - loss: 0.3109 - acc: 0.8664
Epoch 20/100
 - 0s - loss: 0.3055 - acc: 0.8664
Epoch 21/100
 - 0s - loss: 0.3071 - acc: 0.8597
Epoch 22/100
 - 0s - loss: 0.3086 - acc: 0.8842
Epoch 23/100
 - 0s - loss: 0.2974 - acc: 0.8708
Epoch 24/100
 - 0s - loss: 0.2875 - acc: 0.8708
Epoch 25/100
 - 0s - loss: 0.2806 - acc: 0.8864
Epoch 26/100
 - 0s - loss: 0.2810 - acc: 0.8708
Epoch 27/100
 - 0s - loss: 0.2719 - acc: 0.8909
Epoch 28/100
 - 0s - loss: 0.2708 - acc: 0.8820
Epoch 29/100
 - 0s - loss: 0.2624 - acc: 0.8886
Epoch 30/100
 - 0s - loss: 0.2879 - acc: 0.8753
Epoch 31/100
 - 0s - loss: 0.2700 - acc: 0.8820
Epoch 32/100
 - 0s - loss: 0.2551 - acc: 0.8886
Epoch 33/100
 - 0s - loss: 0.2473 - acc: 0.8976
Epoch 34/100
 - 0s - loss: 0.2416 - acc: 0.9065
Epoch 35/100
 - 0s - loss: 0.2512 - acc: 0.8931
Epoch 36/100
 - 0s - loss: 0.2380 - acc: 0.9020
Epoch 37/100
 - 0s - loss: 0.2886 - acc: 0.8686
Epoch 38/100
 - 0s - loss: 0.2509 - acc: 0.8820
Epoch 39/100
 - 0s - loss: 0.2336 - acc: 0.8931
Epoch 40/100
 - 0s - loss: 0.2273 - acc: 0.9042
Epoch 41/100
 - 0s - loss: 0.2198 - acc: 0.9042
Epoch 42/100
 - 0s - loss: 0.2492 - acc: 0.9042
Epoch 43/100
 - 0s - loss: 0.2339 - acc: 0.8797
Epoch 44/100
 - 0s - loss: 0.2198 - acc: 0.9087
Epoch 45/100
 - 0s - loss: 0.2419 - acc: 0.9020
Epoch 46/100
 - 0s - loss: 0.2308 - acc: 0.8909
Epoch 47/100
 - 0s - loss: 0.2117 - acc: 0.9198
Epoch 48/100
 - 0s - loss: 0.2036 - acc: 0.9198
Epoch 49/100
 - 0s - loss: 0.1960 - acc: 0.9220
Epoch 50/100
 - 0s - loss: 0.1917 - acc: 0.9265
Epoch 51/100
 - 0s - loss: 0.1890 - acc: 0.9198
Epoch 52/100
 - 0s - loss: 0.2062 - acc: 0.9176
Epoch 53/100
 - 0s - loss: 0.2059 - acc: 0.9065
Epoch 54/100
 - 0s - loss: 0.1915 - acc: 0.9310
Epoch 55/100
 - 0s - loss: 0.1821 - acc: 0.9243
Epoch 56/100
 - 0s - loss: 0.1783 - acc: 0.9332
Epoch 57/100
 - 0s - loss: 0.1795 - acc: 0.9310
Epoch 58/100
 - 0s - loss: 0.1778 - acc: 0.9220
Epoch 59/100
 - 0s - loss: 0.1715 - acc: 0.9310
Epoch 60/100
 - 0s - loss: 0.1673 - acc: 0.9421
Epoch 61/100
 - 0s - loss: 0.1655 - acc: 0.9421
Epoch 62/100
 - 0s - loss: 0.1593 - acc: 0.9488
Epoch 63/100
 - 0s - loss: 0.1562 - acc: 0.9465
Epoch 64/100
 - 0s - loss: 0.1723 - acc: 0.9421
Epoch 65/100
 - 0s - loss: 0.1658 - acc: 0.9488
Epoch 66/100
 - 0s - loss: 0.1553 - acc: 0.9465
Epoch 67/100
 - 0s - loss: 0.1509 - acc: 0.9532
Epoch 68/100
 - 0s - loss: 0.1468 - acc: 0.9488
Epoch 69/100
 - 0s - loss: 0.1427 - acc: 0.9532
Epoch 70/100
 - 0s - loss: 0.1538 - acc: 0.9510
Epoch 71/100
 - 0s - loss: 0.1445 - acc: 0.9488
Epoch 72/100
 - 0s - loss: 0.1381 - acc: 0.9532
Epoch 73/100
 - 0s - loss: 0.1348 - acc: 0.9532
Epoch 74/100
 - 0s - loss: 0.1332 - acc: 0.9532
Epoch 75/100
 - 0s - loss: 0.1318 - acc: 0.9555
Epoch 76/100
 - 0s - loss: 0.1261 - acc: 0.9577
Epoch 77/100
 - 0s - loss: 0.1539 - acc: 0.9421
Epoch 78/100
 - 0s - loss: 0.1445 - acc: 0.9399
Epoch 79/100
 - 0s - loss: 0.1399 - acc: 0.9376
Epoch 80/100
 - 0s - loss: 0.1686 - acc: 0.9354
Epoch 81/100
 - 0s - loss: 0.1458 - acc: 0.9399
Epoch 82/100
 - 0s - loss: 0.1277 - acc: 0.9555
Epoch 83/100
 - 0s - loss: 0.1203 - acc: 0.9599
Epoch 84/100
 - 0s - loss: 0.1195 - acc: 0.9688
Epoch 85/100
 - 0s - loss: 0.1150 - acc: 0.9621
Epoch 86/100
 - 0s - loss: 0.1131 - acc: 0.9599
Epoch 87/100
 - 0s - loss: 0.1104 - acc: 0.9710
Epoch 88/100
 - 0s - loss: 0.1679 - acc: 0.9332
Epoch 89/100
 - 0s - loss: 0.1464 - acc: 0.9532
Epoch 90/100
 - 0s - loss: 0.1152 - acc: 0.9599
Epoch 91/100
 - 0s - loss: 0.1081 - acc: 0.9599
Epoch 92/100
 - 0s - loss: 0.1043 - acc: 0.9710
Epoch 93/100
 - 0s - loss: 0.1096 - acc: 0.9555
Epoch 94/100
 - 0s - loss: 0.1212 - acc: 0.9465
Epoch 95/100
 - 0s - loss: 0.1083 - acc: 0.9577
Epoch 96/100
 - 0s - loss: 0.1018 - acc: 0.9599
Epoch 97/100
 - 0s - loss: 0.0977 - acc: 0.9755
Epoch 98/100
 - 0s - loss: 0.0961 - acc: 0.9688
Epoch 99/100
 - 0s - loss: 0.0945 - acc: 0.9755
Epoch 100/100
 - 0s - loss: 0.0912 - acc: 0.9710

In [11]:
model1_loss, model1_accuracy = model1.evaluate(X1_test_scaled, y1_test_categorical, verbose=2)
print(f"Normal Neural Network with data - Loss: {model1_loss}, Accuracy: {model1_accuracy}")

model2_loss, model2_accuracy = model2.evaluate(X2_test_scaled, y2_test_categorical, verbose=2)
print(f"Normal Neural Network with/out data - Loss: {model2_loss}, Accuracy: {model2_accuracy}")

Normal Neural Network with data - Loss: 0.8644619189299546, Accuracy: 0.8181818158595593
Normal Neural Network with/out data - Loss: 0.6731449913978577, Accuracy: 0.7666666634877523

In [12]:
model1.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_1 (Dense)              (None, 100)               1200
_________________________________________________________________
dense_2 (Dense)              (None, 100)               10100
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 202
=================================================================
Total params: 11,502
Trainable params: 11,502
Non-trainable params: 0
_________________________________________________________________

In [13]:
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_4 (Dense)              (None, 100)               1200
_________________________________________________________________
dense_5 (Dense)              (None, 100)               10100
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 202
=================================================================
Total params: 11,502
Trainable params: 11,502
Non-trainable params: 0
_________________________________________________________________